FROM oven/bun

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN bun install --filter frontend

ARG NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

RUN bun x turbo run build --filter=frontend

EXPOSE 3000

CMD ["bun", "run", "start:frontend"]